force-app/main/default/objects/CowinVaccine__c/CowinVaccine__c.object-meta.xml
<CustomObject>
    <label>Cowin Vaccine</label>
    <nameField>
        <displayFormat>CO-{0000000000}</displayFormat>
        <label>Cowin Vaccine Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cowin Vaccines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CowinVaccine__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CowinVaccine__c/fields/District_Id__c.field-meta.xml
<CustomField>
    <fullName>District_Id__c</fullName>
    <label>District Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CowinVaccine__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Andaman and Nicobar Islands</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Andhra Pradesh</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Arunachal Pradesh</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Assam</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Bihar</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Chandigarh</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Chhattisgarh</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Dadra and Nagar Haveli</label>
            </value>
            <value>
                <fullName>37</fullName>
                <label>Daman and Diu</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Delhi</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Goa</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Gujarat</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Haryana</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Himachal Pradesh</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Jammu and Kashmir</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Jharkhand</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Karnataka</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Kerala</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Ladakh</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Lakshadweep</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Madhya Pradesh</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>Maharashtra</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>Manipur</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>Meghalaya</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Mizoram</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>Nagaland</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>Odisha</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>Puducherry</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>Punjab</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>Rajasthan</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CowinVaccineConroller.cls
/**
 * @description CowinVaccineConroller class is the controller for the LWC component
 * 
 * @author      Salesforce Binge
 * @website     https://salesforcebinge.com/
 */
public without sharing class CowinVaccineConroller {
    
    @AuraEnabled(cacheable=true)
    public static List<CowinVaccine__c> getVaccineDistricts() {
        return [SELECT Id, State__c, District__c, District_Id__c
                FROM CowinVaccine__c 
                ORDER BY District__c ASC
                LIMIT 1000];
    }

    @AuraEnabled(cacheable=true)
    public static List<CowinVaccine__c> findDistricts(String searchKey) {
        String key = '%' + searchKey + '%';
        return [
            SELECT Id, State__c, District__c, District_Id__c
            FROM CowinVaccine__c
            WHERE District__c LIKE :key
            ORDER BY District__c ASC
            //WITH SECURITY_ENFORCED
            LIMIT 1000
        ];
    }

    @AuraEnabled
    public static List<GenericVaccineDataWrapper> calendarByDistrict (String districtId, String vaccDate) {
        List<CalendarByDistrictResponse.Center> vaccineSessions = new List<CalendarByDistrictResponse.Center>();
        List<GenericVaccineDataWrapper> vaccineWrapperList = new List<GenericVaccineDataWrapper>();

        String url = 'https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict?district_id='+districtId+'&date='+vaccDate;
        HttpResponse response = CowinVaccineRequest.coWinVaccineGetCall(url);

        if (response.getStatusCode() == 200) {
            String responseBodyDate = response.getBody().replaceAll('\"date\":', '\"date_x\":');
            String responseBodyDateLong = responseBodyDate.replaceAll('\"long\":', '\"long_x\":');
            String responseBody = responseBodyDateLong.replaceAll('\"from\":', '\"from_x\":');
            CalendarByDistrictResponse sessionResponse = (CalendarByDistrictResponse)JSON.deserialize(responseBody, CalendarByDistrictResponse.class);

            for (CalendarByDistrictResponse.Center vaccineCenter : sessionResponse.centers) {
                if (! vaccineCenter.sessions.isEmpty()) {
                    for (CalendarByDistrictResponse.Session vaccineSession : vaccineCenter.sessions) {
                        GenericVaccineDataWrapper vaccineWrapper = new GenericVaccineDataWrapper ();
                        vaccineWrapper.name = vaccineCenter.name;
                        vaccineWrapper.address = vaccineCenter.address;
                        vaccineWrapper.block_name = vaccineCenter.block_name;
                        vaccineWrapper.fee_type = vaccineCenter.fee_type;
                        vaccineWrapper.state_name = vaccineCenter.state_name;
                        vaccineWrapper.district_name = vaccineCenter.district_name;
                        vaccineWrapper.vaccine = vaccineSession.vaccine;
                        vaccineWrapper.min_age_limit = vaccineSession.min_age_limit;
                        vaccineWrapper.available_capacity = vaccineSession.available_capacity;
                        vaccineWrapper.date_x = vaccineSession.date_x;
                        vaccineWrapper.pincode = vaccineCenter.pincode;
                        vaccineWrapperList.add(vaccineWrapper);
                    }
                }
            }
        }
        return vaccineWrapperList;
    }

    @AuraEnabled
    public static List<GenericVaccineDataWrapper> calendarByPin (String pincode, String vaccDate) {
        List<GenericVaccineDataWrapper> vaccineWrapperList = new List<GenericVaccineDataWrapper>();
        List<CalendarByPinResponse.Center> vaccineSessions = new List<CalendarByPinResponse.Center>();

        String url = 'https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByPin?pincode='+pincode+'&date='+vaccDate;
        HttpResponse response = CowinVaccineRequest.coWinVaccineGetCall(url);

        if (response.getStatusCode() == 200) {
            String responseBodyDate = response.getBody().replaceAll('\"date\":', '\"date_x\":');
            String responseBodyDateLong = responseBodyDate.replaceAll('\"long\":', '\"long_x\":');
            String responseBody = responseBodyDateLong.replaceAll('\"from\":', '\"from_x\":');
            CalendarByPinResponse sessionResponse = (CalendarByPinResponse)JSON.deserialize(responseBody, CalendarByPinResponse.class);

            for (CalendarByPinResponse.Center vaccineCenter : sessionResponse.centers) {
                if (! vaccineCenter.sessions.isEmpty()) {
                    for (CalendarByPinResponse.Session vaccineSession : vaccineCenter.sessions) {
                        GenericVaccineDataWrapper vaccineWrapper = new GenericVaccineDataWrapper ();
                        vaccineWrapper.name = vaccineCenter.name;
                        vaccineWrapper.address = vaccineCenter.address;
                        vaccineWrapper.block_name = vaccineCenter.block_name;
                        vaccineWrapper.fee_type = vaccineCenter.fee_type;
                        vaccineWrapper.state_name = vaccineCenter.state_name;
                        vaccineWrapper.district_name = vaccineCenter.district_name;
                        vaccineWrapper.vaccine = vaccineSession.vaccine;
                        vaccineWrapper.min_age_limit = vaccineSession.min_age_limit;
                        vaccineWrapper.available_capacity = vaccineSession.available_capacity;
                        vaccineWrapper.date_x = vaccineSession.date_x;
                        vaccineWrapper.pincode = vaccineCenter.pincode;
                        vaccineWrapperList.add(vaccineWrapper);
                    }
                }
            }
        }
        return vaccineWrapperList;
    }
}